<?php
$imgbaseUrl = $this->baseUrl().'/img/';
$baseUrl = $this->baseUrl();
?>
<!DOCTYPE html>
<html id="XenForo" dir="LTR" class="Public LoggedIn NoSidebar  Responsive hasJs NoTouch HasDragDrop" xmlns:fb="http://www.facebook.com/2008/fbml" lang="en-US"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Add Game Profile | U1stGames</title>
	
	
	<link rel="stylesheet" href="<?php echo $baseUrl .'/css/css_003.css'; ?>">
	<link rel="stylesheet" href="<?php echo $baseUrl .'/css/css_002.css'; ?>">	
	<link href="<?php echo $baseUrl . '/css/font-awesome.css'; ?>" rel="stylesheet">
	<link href="<?php echo $baseUrl . '/css/default.css'; ?>" rel="stylesheet">
	<link href="<?php echo $baseUrl . '/css/bootstrap.min.css'; ?>" rel="stylesheet">
	<link href="<?php echo $baseUrl . '/css/css.css'; ?>" rel="stylesheet" type="text/css">

	<script src="<?php echo $baseUrl . '/js/jquery-1.js'; ?>"></script>	
	<script src="<?php echo $baseUrl . '/js/xenforo.js'; ?>"></script>
	<script src="<?php echo $baseUrl . '/js/quick_reply_profile.js'; ?>"></script>
	<script src="<?php echo $baseUrl . '/owl-carousel/jquery-1.9.1.min.js';?>"></script>
	
	<style>
	.ctrlUnit dl
	{
	float:left;
	}
	</style>

</head>

<body data-twttr-rendered="true">

<div class="topHelper"></div>
<div id="headerMover">
	<div id="headerProxy"></div>

<div id="content" class="member_view">
	<div class="pageWidth">
		<div class="pageContent">
			<!-- main content area -->
	<?php include 'include/breadcrumbtop.php';?>
						
					
 <div class="row">
      <div class="content">

 <div class="row">
      <div class="col-lg-8" style="padding:0px;">
        <div class="right_content"> 
          
       
          
          <!----Add Part------------>
		   <div class="add"> <img src="#" width="100%" height="100%" title="add box" class="img-rounded"> </div>
         
          <div class="col-lg-12">
              <div class="col-lg-1" style="height:50px; line-height:50px"></div>
            
          </div>
          <!----right images content part------------>
           <div class="col-lg-12">
        <form action="http://localhost/repo/u1stgames/u1stgames/web_root/games/insert/" method="post" class="xenForm AutoValidator" data-normalsubmit="1">
	

	<dl class="ctrlUnit">
		<dt><label for="ctrl_username">Name:</label></dt>
		<dd>
			<input name="username" class="textCtrl" id="ctrl_username" autofocus="true" autocomplete="off" type="text"><label style="display: none;" for="ctrl_username" class="formValidationInlineError inlineError">Usernames must be unique. The specified username is already in use.</label>
			<p class="explain">This is the name that will be shown with your messages. You may use any name you wish. Once set, this cannot be changed.</p>
		</dd>
	</dl>

	<dl class="ctrlUnit">
		<dt><label for="ctrl_email">Email:</label></dt>
		<dd><input name="email" dir="ltr" class="textCtrl" id="ctrl_email" type="email"><label style="display: none;" for="ctrl_email" class="formValidationInlineError inlineError">Email addresses must be unique. The specified email address is already in use.</label></dd>
	</dl>
	
		<dl class="ctrlUnit OptOut">
		<dt>Date of Birth:</dt>
		<dd>
			<ul dir="ltr" id="helper_birthday">
<li><select name="dob_month" class="textCtrl autoSize">
	<option value="0">&nbsp;</option>
	<option value="1">January</option>
	<option value="2">February</option>
	<option value="3">March</option>
	<option value="4">April</option>
	<option value="5">May</option>
	<option value="6">June</option>
	<option value="7">July</option>
	<option value="8">August</option>
	<option value="9">September</option>
	<option value="10">October</option>
	<option value="11">November</option>
	<option value="12">December</option>
</select></li>
<li><input name="dob_day" class="textCtrl autoSize" placeholder="Day" size="2" maxlength="2" type="text"></li>
<li><input name="dob_year" class="textCtrl autoSize" placeholder="Year" size="4" maxlength="4" type="text"></li>
</ul>
			<p class="explain">Your date of birth is required.</p>
		</dd>
	</dl>
	
	<input name="gender" value="" type="hidden">
	
	
	

	<dl class="ctrlUnit">
		<dt><label for="ctrl_timezone">Time zone:</label></dt>
		<dd>
			<select name="timezone" class="textCtrl AutoTimeZone OptOut" id="ctrl_timezone">
				
					<option value="Pacific/Midway">(UTC-11:00) American Samoa</option>
				
					<option value="Pacific/Apia">(UTC-11:00) Apia, Samoa</option>
				
					<option value="Pacific/Honolulu">(UTC-10:00) Hawaii</option>
				
					<option value="Pacific/Marquesas">(UTC-09:30) Marquesas Islands</option>
				
					<option value="America/Anchorage">(UTC-09:00) Alaska</option>
				
					<option value="America/Los_Angeles">(UTC-08:00) Pacific Time (US &amp; Canada)</option>
				
					<option value="America/Santa_Isabel">(UTC-08:00) Baja California</option>
				
					<option value="America/Tijuana">(UTC-08:00) Tijuana</option>
				
					<option value="America/Denver">(UTC-07:00) Mountain Time (US &amp; Canada)</option>
				
					<option value="America/Chihuahua">(UTC-07:00) Chihuahua, La Paz, Mazatlan</option>
				
					<option value="America/Phoenix">(UTC-07:00) Arizona</option>
				
					<option value="America/Chicago">(UTC-06:00) Central Time (US &amp; Canada)</option>
				
					<option value="America/Belize">(UTC-06:00) Saskatchewan, Central America</option>
				
					<option value="America/Mexico_City">(UTC-06:00) Guadalajara, Mexico City, Monterrey</option>
				
					<option value="Pacific/Easter">(UTC-06:00) Easter Island</option>
				
					<option value="America/New_York">(UTC-05:00) Eastern Time (US &amp; Canada)</option>
				
					<option value="America/Havana">(UTC-05:00) Cuba</option>
				
					<option value="America/Bogota">(UTC-05:00) Bogota, Lima, Quito</option>
				
					<option value="America/Caracas">(UTC-04:30) Caracas</option>
				
					<option value="America/Halifax">(UTC-04:00) Atlantic Time (Canada)</option>
				
					<option value="America/Goose_Bay">(UTC-04:00) Atlantic Time (Goose Bay)</option>
				
					<option value="America/Asuncion">(UTC-04:00) Asuncion</option>
				
					<option value="America/Santiago">(UTC-04:00) Santiago</option>
				
					<option value="America/Cuiaba">(UTC-04:00) Cuiaba</option>
				
					<option value="America/La_Paz">(UTC-04:00) Georgetown, La Paz, Manaus, San Juan</option>
				
					<option value="Atlantic/Stanley">(UTC-04:00) Falkland Islands</option>
				
					<option value="America/St_Johns">(UTC-03:30) Newfoundland</option>
				
					<option value="America/Argentina/Buenos_Aires">(UTC-03:00) Buenos Aires</option>
				
					<option value="America/Argentina/San_Luis">(UTC-03:00) San Luis</option>
				
					<option value="America/Argentina/Mendoza">(UTC-03:00) Argentina, Cayenne, Fortaleza</option>
				
					<option value="America/Godthab">(UTC-03:00) Greenland</option>
				
					<option value="America/Montevideo">(UTC-03:00) Montevideo</option>
				
					<option value="America/Sao_Paulo">(UTC-03:00) Brasilia</option>
				
					<option value="America/Miquelon">(UTC-03:00) Saint Pierre and Miquelon</option>
				
					<option value="America/Noronha">(UTC-02:00) Mid-Atlantic</option>
				
					<option value="Atlantic/Cape_Verde">(UTC-01:00) Cape Verde Is.</option>
				
					<option value="Atlantic/Azores">(UTC-01:00) Azores</option>
				
					<option value="Europe/London">(UTC) Dublin, Edinburgh, Lisbon, London</option>
				
					<option value="Africa/Casablanca">(UTC) Casablanca</option>
				
					<option value="Atlantic/Reykjavik">(UTC) Monrovia, Reykjavik</option>
				
					<option value="Europe/Amsterdam">(UTC+01:00) Central European Time</option>
				
					<option value="Africa/Algiers">(UTC+01:00) West Central Africa</option>
				
					<option value="Africa/Windhoek">(UTC+01:00) Windhoek</option>
				
					<option value="Africa/Tunis">(UTC+01:00) Tunis</option>
				
					<option value="Europe/Athens">(UTC+02:00) Eastern European Time</option>
				
					<option value="Africa/Johannesburg">(UTC+02:00) South Africa Standard Time</option>
				
					<option value="Asia/Amman">(UTC+02:00) Amman</option>
				
					<option value="Asia/Beirut">(UTC+02:00) Beirut</option>
				
					<option value="Africa/Cairo">(UTC+02:00) Cairo</option>
				
					<option value="Asia/Jerusalem">(UTC+02:00) Jerusalem</option>
				
					<option value="Europe/Minsk">(UTC+02:00) Minsk</option>
				
					<option value="Asia/Gaza">(UTC+02:00) Gaza</option>
				
					<option value="Asia/Damascus">(UTC+02:00) Syria</option>
				
					<option value="Africa/Nairobi">(UTC+03:00) Nairobi, Baghdad, Kuwait, Qatar, Riyadh</option>
				
					<option value="Europe/Kaliningrad">(UTC+03:00) Kaliningrad</option>
				
					<option value="Asia/Tehran">(UTC+03:30) Tehran</option>
				
					<option value="Europe/Moscow">(UTC+04:00) Moscow, St. Petersburg, Volgograd</option>
				
					<option value="Asia/Dubai">(UTC+04:00) Abu Dhabi, Muscat, Tbilisi</option>
				
					<option value="Asia/Yerevan">(UTC+04:00) Yerevan</option>
				
					<option value="Asia/Baku">(UTC+04:00) Baku</option>
				
					<option value="Indian/Mauritius">(UTC+04:00) Mauritius</option>
				
					<option value="Asia/Kabul">(UTC+04:30) Kabul</option>
				
					<option value="Asia/Tashkent">(UTC+05:00) Tashkent, Karachi</option>
				
					<option selected="selected" value="Asia/Kolkata">(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi</option>
				
					<option value="Asia/Kathmandu">(UTC+05:45) Kathmandu</option>
				
					<option value="Asia/Dhaka">(UTC+06:00) Astana, Dhaka</option>
				
					<option value="Asia/Yekaterinburg">(UTC+06:00) Ekaterinburg</option>
				
					<option value="Asia/Almaty">(UTC+06:00) Almaty, Bishkek, Qyzylorda</option>
				
					<option value="Asia/Rangoon">(UTC+06:30) Yangon (Rangoon)</option>
				
					<option value="Asia/Bangkok">(UTC+07:00) Bangkok, Hanoi, Jakarta</option>
				
					<option value="Asia/Novosibirsk">(UTC+07:00) Novosibirsk</option>
				
					<option value="Asia/Hong_Kong">(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi</option>
				
					<option value="Asia/Krasnoyarsk">(UTC+08:00) Krasnoyarsk</option>
				
					<option value="Asia/Singapore">(UTC+08:00) Kuala Lumpur, Singapore</option>
				
					<option value="Australia/Perth">(UTC+08:00) Perth</option>
				
					<option value="Asia/Irkutsk">(UTC+09:00) Irkutsk</option>
				
					<option value="Asia/Tokyo">(UTC+09:00) Osaka, Sapporo, Tokyo</option>
				
					<option value="Asia/Seoul">(UTC+09:00) Seoul</option>
				
					<option value="Australia/Adelaide">(UTC+09:30) Adelaide</option>
				
					<option value="Australia/Darwin">(UTC+09:30) Darwin</option>
				
					<option value="Australia/Brisbane">(UTC+10:00) Brisbane, Guam</option>
				
					<option value="Australia/Sydney">(UTC+10:00) Sydney, Melbourne, Hobart</option>
				
					<option value="Asia/Yakutsk">(UTC+10:00) Yakutsk</option>
				
					<option value="Pacific/Noumea">(UTC+11:00) Solomon Is., New Caledonia</option>
				
					<option value="Asia/Vladivostok">(UTC+11:00) Vladivostok</option>
				
					<option value="Pacific/Norfolk">(UTC+11:30) Norfolk Island</option>
				
					<option value="Asia/Anadyr">(UTC+12:00) Anadyr, Kamchatka</option>
				
					<option value="Pacific/Auckland">(UTC+12:00) Auckland, Wellington</option>
				
					<option value="Pacific/Fiji">(UTC+12:00) Fiji</option>
				
					<option value="Asia/Magadan">(UTC+12:00) Magadan</option>
				
					<option value="Pacific/Chatham">(UTC+12:45) Chatham Islands</option>
				
					<option value="Pacific/Tongatapu">(UTC+13:00) Nuku'alofa</option>
				
					<option value="Pacific/Kiritimati">(UTC+14:00) Kiritimati</option>
				
			</select>
		</dd>
	</dl>

<input name="agree" value="1" type="hidden"> 

	

	<dl class="ctrlUnit submitUnit">
		<dt></dt>
		<dd>
			
			
				<ul>
					<li>
						
						<ul class="" id="ctrl_agree_Disabler">
							<li><input value="Sign up" accesskey="s" class="button primary" id="SubmitButton" type="submit"> 
				
							</li>
						</ul>						
					</li>
				</ul>
			
		</dd>
	</dl>

	
</form>
 </div>
		  
		  
        </div>
      </div>
      
      <!----Left content part------------>
      <div class="col-lg-4" style="padding:0px;">
        <div class="left_content"> 
          
          <!----Add Box------------>
          <div class="col-lg-12">
            <div class="add_box"> <img src="#" width="100%" height="100%" title="add box" class="img-rounded"> </div>
          </div>
          
          <!----Login Panel------------>
          <div class="col-lg-12">
            <div class="login_box">
              <h3>Login</h3>
              <div class="col-lg-12">
                <div class="form_box"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
     
		 </div>
        </div>
		
		
<?php include 'include/breadcrumbottom.php';?>						
		</div>
	</div>
</div>

<?php include 'include/header.php';?>

</div>

<?php include 'include/footer.php';?>
			</body>
			</html>