<?php
$imgbaseUrl = $this->baseUrl().'/img/';
$baseUrl = $this->baseUrl();
?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>U1Game | Games</title>
<link href="<?php echo $baseUrl . '/css/bootstrap.min.css'; ?>" media="all" rel="stylesheet" type="text/css" />
<link href="<?php echo $baseUrl . '/css/bootstrap-theme.min.css'; ?>" media="all" rel="stylesheet" type="text/css" />
<link href="<?php echo $baseUrl . '/css/default.css'; ?>" media="all" rel="stylesheet" type="text/css" />
<script src="<?php echo $baseUrl . '/owl-carousel/jquery-1.9.1.min.js';?>"></script>
<style>
#overflow
{
width: 60px;
white-space: nowrap;
display:inline-block;
height:20px;
text-overflow:ellipsis;
overflow: hidden;
}
</style>
<script>
$(document).ready(function(){
    $("#filter").keyup(function(){
 
        // Retrieve the input field text and reset the count to zero
        var filter = $(this).val(), count = 0;
 
        // Loop through the comment list
        $(".box1").each(function(){
 
            // If the list item does not contain the text phrase fade it out
            if ($(this).text().search(new RegExp(filter, "i")) < 0) {
                $(this).fadeOut();
                
            // Show the list item if the phrase matches and increase the count by 1
            } else {
                $(this).show();
                count++;
            }
        });
 
        // Update the count
        var numberItems = count;
        $("#filter-count").text("Number of Games = "+count);
    });
});
</script>
</head>

<body>
<div class="container-fluid" style="padding:0;">
  <div id="top"></div>
  <div class="container"> 
    
    <!---header--------->
    <header class="header"> 
      
      <!---Logo--------->
      <div class="col-lg-4" style="padding-top:5px;"> <img src=<?php echo $imgbaseUrl . 'logo3.png'?> width="190" height="50"> </div>
      
      <!---Social Icon--------->
      <div class="col-lg-8">
        <div class="col-lg-1 pull-right"><a href="#"><img src=<?php echo $imgbaseUrl .'facebook.png'?> width="30" height="30"></a></div>
        <div class="col-lg-1 pull-right"><a href="#"><img src=<?php echo $imgbaseUrl .'twitter.png'?> width="30" height="30"></a></div>
      </div>
    </header>
    
    <!---Menu Bar--------->
    <div class="row">
      <nav class="menu">
        <ul>
          <li><a href="#">Home</a></li>
          <li><a href="#">Form</a></li>
          <li><a href="#">Resources</a></li>
          <li><a href="#">Games</a></li>
          <li><a href="#">Bonus Feeds</a></li>
          <li><a href="#">Link Exchange</a></li>
        </ul>
      </nav>
    </div>
     <!---Breadcrumb Menu Bar--------->
    <div class="row">
      <div class="col-lg-12">
        <ul class="breadcrumb">
          <li><a href="#">Home</a></li>
          <li><a href="#">Games</a></li>
          <li class="active">Games Name</li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="search_form">
        <div class="col-lg-11">
          <input type="search" placeholder="Search Forums">
        </div>
        <div class="col-lg-1">
          <button type="submit" class="btn btn-default pull-left" style="margin:10px; height:30px; line-height:15px;">go</button>
        </div>
      </div>
    </div>
	
	
	
    <!---- content part------------> 
    <!----Right content part------------>
    <div class="row">
      <div class="col-lg-8" style="padding:0px;">
        <div class="right_content"> 
          
          <!-------breadcrumbs--------->
          <div class="breadcrumbs"></div>
          
          <!----Add Part------------>
          <div class="add"> <img src="#" width="100%" height="100%" title="add box" class="img-rounded"> </div>
          <form id="live-search" action="" class="styled" method="post">
		  <fieldset>
			<input type="text" class="text-input" id="filter" value="" />
			<span id="filter-count"></span>
		  </fieldset>
		  </form>
          <!----right images content part------------>
          
          <div class="col-lg-12">
		  <?php $datas = $this->datas;
		  
			for($i = 0; $i<= count($datas)-1;$i++){ ?>
            <div class="box1"> <img class = "gameimage" src="<?=$datas[$i]->logo;?>" width="60" height="60" title = "<?=$datas[$i]->gamename;?>">
              <div id = "overflow" class="gamename"><?=$datas[$i]->gamename;?></div>
            </div>
			<?php } ?>
          </div>
        </div>
      </div>
      
  
      <!----Left content part------------>
      <div class="col-lg-4" style="padding:0px;">
        <div class="left_content"> 
          
          <!----Add Box------------>
          <div class="col-lg-12">
            <div class="add_box"> <img src="#" width="100%" height="100%" title="add box" class="img-rounded"> </div>
          </div>
          
          <!----Login Panel------------>
          <div class="col-lg-12">
            <div class="login_box">
              <h3>Login</h3>
              <div class="col-lg-12">
                <div class="form_box"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <!-------------footer----------->
    <div class="row">
      <footer class="footer">
        <div class="sub_footer">
          <ul>
            <li><a href="#">FAQ</a></li>
            <li><a href="#">Developers</a></li>
            <li><a href="#">Terms</a></li>
            <li><a href="#">Thanks</a></li>
            <li><a href="#">Webmaster</a></li>
          </ul>
        </div>
      </footer>
    </div>
  </div>
</div>
</body>
</html>
