<?php
$imgbaseUrl = $this->baseUrl().'/img/';
$baseUrl = $this->baseUrl();
?>
<!DOCTYPE html>
<html id="XenForo" dir="LTR" class="Public LoggedIn NoSidebar  Responsive hasJs NoTouch HasDragDrop" xmlns:fb="http://www.facebook.com/2008/fbml" lang="en-US"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Game Profiles | U1stGames</title>
	
	
	<link rel="stylesheet" href="<?php echo $baseUrl .'/css/css_003.css'; ?>">
	<link rel="stylesheet" href="<?php echo $baseUrl .'/css/css_002.css'; ?>">	
	<link href="<?php echo $baseUrl . '/css/font-awesome.css'; ?>" rel="stylesheet">
	<link href="<?php echo $baseUrl . '/css/default.css'; ?>" rel="stylesheet">
	<link href="<?php echo $baseUrl . '/css/bootstrap.min.css'; ?>" rel="stylesheet">
	<link href="<?php echo $baseUrl . '/css/css.css'; ?>" rel="stylesheet" type="text/css">

	<script src="<?php echo $baseUrl . '/js/jquery-1.js'; ?>"></script>	
	<script src="<?php echo $baseUrl . '/js/xenforo.js'; ?>"></script>
	<script src="<?php echo $baseUrl . '/js/quick_reply_profile.js'; ?>"></script>
	<script src="<?php echo $baseUrl . '/owl-carousel/jquery-1.9.1.min.js';?>"></script>
<style>
#overflow
{
width: 60px;
white-space: nowrap;
display:inline-block;
height:20px;
text-overflow:ellipsis;
overflow: hidden;
}
</style>
<script>
$(document).ready(function(){
    $("#filter").keyup(function(){
 
        // Retrieve the input field text and reset the count to zero
        var filter = $(this).val(), count = 0;
 
        // Loop through the comment list
        $(".box1").each(function(){
 
            // If the list item does not contain the text phrase fade it out
            if ($(this).text().search(new RegExp(filter, "i")) < 0) {
                $(this).fadeOut();
                
            // Show the list item if the phrase matches and increase the count by 1
            } else {
                $(this).show();
                count++;
            }
        });
 
        // Update the count
        var numberItems = count;
        $("#filter-count").text("Number of Games = "+count);
    });
});
</script>
</head>

<body data-twttr-rendered="true">

<div class="topHelper"></div>
<div id="headerMover">
	<div id="headerProxy"></div>

<div id="content" class="member_view">
	<div class="pageWidth">
		<div class="pageContent">
			<!-- main content area -->
	<?php include 'include/breadcrumbtop.php';?>
						
					
 <div class="row">
      <div class="content">

 <div class="row">
      <div class="col-lg-8" style="padding:0px;">
        <div class="right_content"> 
          
       
          
          <!----Add Part------------>
		   <div class="add"> <img src="#" width="100%" height="100%" title="add box" class="img-rounded"> </div>
         
          <div class="col-lg-12">
          
              <div class="col-lg-1" style="height:50px; line-height:50px">Search</div>
			  <form id="live-search" method="post" class="col-lg-9" placeholder="search games">
              <input type="search" class="col-lg-9" placeholder="search games" type="text" id="filter">
  
            </form>
          </div>
          <!----right images content part------------>
          
         <div class="col-lg-12">
		  <?php $datas = $this->datas;
		  
			for($i = 0; $i<= count($datas)-1;$i++){ ?>
            <div class="box1"> <img class = "gameimage" src="<?=$datas[$i]->logo;?>" width="60" height="60" title = "<?=$datas[$i]->gamename;?>">
              <div id = "overflow" class="gamename"><?=$datas[$i]->gamename;?></div>
            </div>
			<?php } ?>
          </div>
		  
		  
        </div>
      </div>
      
      <!----Left content part------------>
      <div class="col-lg-4" style="padding:0px;">
        <div class="left_content"> 
          
          <!----Add Box------------>
          <div class="col-lg-12">
            <div class="add_box"> <img src="#" width="100%" height="100%" title="add box" class="img-rounded"> </div>
          </div>
          
          <!----Login Panel------------>
          <div class="col-lg-12">
            <div class="login_box">
              <h3>Login</h3>
              <div class="col-lg-12">
                <div class="form_box"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
     
		 </div>
        </div>
		
		
<?php include 'include/breadcrumbottom.php';?>						
		</div>
	</div>
</div>

<?php include 'include/header.php';?>

</div>

<?php include 'include/footer.php';?>
			</body>
			</html>