<?php
$imgbaseUrl = $this->baseUrl().'/img/';
$baseUrl = $this->baseUrl();

?>
<!DOCTYPE html>
<html id="XenForo" dir="LTR" class="Public LoggedIn NoSidebar  Responsive hasJs NoTouch HasDragDrop" xmlns:fb="http://www.facebook.com/2008/fbml" lang="en-US"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Home | U1stGames</title>
	
	
	<link rel="stylesheet" href="css/css_003.css">
	<link rel="stylesheet" href="css/css_002.css">	
	<link href="css/font-awesome.css" rel="stylesheet">
	<link href="css/default.css" rel="stylesheet">
	<link href="css/bootstrap.min.css" rel="stylesheet">
	<link href="css/css.css" rel="stylesheet" type="text/css">
	<script src="/owl-carousel/jquery-1.9.1.min.js"></script>
	<script src="js/jquery-1.js"></script>	
	<script src="js/xenforo.js"></script>
	<script src="js/quick_reply_profile.js"></script>
	
	<!-- Important Owl stylesheet -->
<link rel="stylesheet" href="owl-carousel/owl.carousel.css">
 
<!-- Default Theme -->
<link rel="stylesheet" href="owl-carousel/owl.theme.css">
 
<!-- jQuery 1.7+ -->
<script src="owl-carousel/jquery-1.9.1.min.js"></script>
 
<!-- Include js plugin -->
<script src="owl-carousel/owl.carousel.js"></script>

<script>
    $(document).ready(function() {
     
    $("#owl-example").owlCarousel();
     
    });
</script>

</head>

<body data-twttr-rendered="true">

<div class="topHelper"></div>
<div id="headerMover">
	<div id="headerProxy"></div>

<div id="content" class="member_view">
	<div class="pageWidth">
		<div class="pageContent">
			<!-- main content area -->
		
		<?php include '/include/breadcrumbtop.php';?>
						
					
 <div class="row">
      <div class="content">

 <div class="row">
          <div class="col-lg-8 col-lg-offset-2">
            <div class="add"></div>
          </div>
        </div>

<div class="row">
          <div class="col-lg-8 col-lg-offset-2" style="text-align:center;">
            <h2>Top 5 Games This Week</h2>
          </div>
        </div>

<div class="row">
          <div class="banner">
		  <div id="owl-example" class="owl-carousel">
		  	<?php $datas = $this->datas;
		  
     for($i = 0; $i<= count($datas)-1;$i++){ ?>
            <div class="col-lg-2"> 
			
			<img src="<?=$datas[$i]->hdlogo;?>" width="150" height="190">
			
			</div>
     
	 <?php } ?>
			</div>
          </div>
        </div>
		
		
		
		 <div class="row">
          <div class="col-lg-12">
            <div class="u1_container">
              <div class="col-lg-4">
                <div class="box">
                  <div class="col-lg-12" style="text-align:center"> <img src="#" width="100" height="100"/> </div>
                  <div class="col-lg-12" style="text-align:center">
                    <h4>Game Profiles</h4>
                  </div>
                  <div class="col-lg-12" style="text-align:center">
                    <p>Our unique game profiles provide information, tips and tricks for all your favourite games. We will be updating this page with new and unique games regularly, so make sure you check it out.
</p>
                  </div>
                  <div class="col-lg-12" style="text-align:center">
                    <div class="btn btn-default">Go!</div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="box">
                  <div class="col-lg-12" style="text-align:center"> <img src="#" width="100" height="100"/> </div>
                  <div class="col-lg-12" style="text-align:center">
                    <h4>Bonus Collectors</h4>
                  </div>
                  <div class="col-lg-12" style="text-align:center">
                    <p>Tired of trawling through your news feed in search of those all important in game bonuses? We have various collectors to help you automatically collect them or simply gather them on one page so you can easily click on the bonuses you desire.
</p>
                  </div>
                  <div class="col-lg-12" style="text-align:center">
                    <div class="btn btn-default">Go!</div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="box">
                  <div class="col-lg-12" style="text-align:center"> <img src="#" width="100" height="100"/> </div>
                  <div class="col-lg-12" style="text-align:center">
                    <h4>Forums</h4>
                  </div>
                  <div class="col-lg-12" style="text-align:center">
                    <p>Whether you're stuck on that difficult level and need help or just want to talk to new friends who play your favourite game, U1stGames' forums is the place for you. Find insightful and interesting conversational topics here.
</p>
                  </div>
                  <div class="col-lg-12" style="text-align:center">
                    <div class="btn btn-default">Go!</div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="box">
                  <div class="col-lg-12" style="text-align:center"> <img src="#" width="100" height="100"/> </div>
                  <div class="col-lg-12" style="text-align:center">
                    <h4>Link Exchange</h4>
                  </div>
                  <div class="col-lg-12" style="text-align:center">
                    <p>Used up all your bonuses but still need more? Link Exchange is where we keep all the free bonuses donated by our users, giving you that extra edge when you require that extra boost to level up.
</p>
                  </div>
                  <div class="col-lg-12" style="text-align:center">
                    <div class="btn btn-default">Go!</div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="box">
                  <div class="col-lg-12" style="text-align:center"> <img src="#" width="100" height="100"/> </div>
                  <div class="col-lg-12" style="text-align:center">
                    <h4>Chat</h4>
                  </div>
                  <div class="col-lg-12" style="text-align:center">
                    <p>Chat we're all about uniting gamers because we know how frustrating it is when you just need to ask someone a quick question so that you can get through that pesky obstacle. Come visit our live chat and connect to u1stGamers from around the world.
</p>
                  </div>
                  <div class="col-lg-12" style="text-align:center">
                    <div class="btn btn-default">Go!</div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="box">
                  <div class="col-lg-12" style="text-align:center"> <img src="#" width="100" height="100"/> </div>
                  <div class="col-lg-12" style="text-align:center">
                    <h4>My Profile</h4>
                  </div>
                  <div class="col-lg-12" style="text-align:center">
                    <p>Create your very own gamer profile and let all U1stGamers know what you're about. Here, you can post about your favourite games, show everyone your achievements and let friends post on your wall.
</p>
                  </div>
                  <div class="col-lg-12" style="text-align:center">
                    <div class="btn btn-default">Go!</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
     
		 </div>
        </div>
		
<?php include '/include/breadcrumbottom.php';?>						
		</div>
	</div>
</div>

<?php include '/include/header.php';?>

</div>

<?php include '/include/footer.php';?>
			</body>
			</html>