 <?php
function ordinal($num) {
    $ones = $num % 10;
    $tens = floor($num / 10) % 10;
    if ($tens == 1) {
        $suff = "th";
    } else {
        switch ($ones) {
            case 1 : $suff = "st"; break;
            case 2 : $suff = "nd"; break;
            case 3 : $suff = "rd"; break;
            default : $suff = "th";
        }
    }
    return $num . $suff;
}		  
		  $datas = $this->datas;
		  
     for($i = 0; $i<= count($datas)-1;$i++){ ?>
    
	<div class="row">
            <div class="col-lg-12" style="height:100px;">
              <div class="col-lg-2"> <img src="<?=$datas[$i]['logo'];?>" width="100" height="100" class="img-rounded"/> </div>
              <div class="col-lg-9">
                <div class="col-lg-12" style="text-align:center;">
                  <h3 style="padding:0px; margin:0px;"><?=$datas[$i]['gamename'];?></h3>
                </div>
                <div class="col-lg-12">
                  <div class="col-lg-4">
                    <h4>Week</h4>
                    <p class="h3"><?=ordinal($datas[$i]['week']);?></p>
                  </div>
                  <div class="col-lg-4">
                    <h4>Month</h4>
                    <p class="h3"><?=ordinal($datas[$i]['month']);?></p>
                  </div>
                  <div class="col-lg-4">
                    <h4>All time</h4>
                    <p class="h3"><?=ordinal($datas[$i]['all']);?></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <hr>
  <?php } ?>