<?php
$imgbaseUrl = $this->baseUrl().'/img/';
$baseUrl = $this->baseUrl();
?>
<!DOCTYPE html>
<html id="XenForo" dir="LTR" class="Public LoggedIn NoSidebar  Responsive hasJs NoTouch HasDragDrop" xmlns:fb="http://www.facebook.com/2008/fbml" lang="en-US"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Leader Board | U1stGames</title>
	
	
	<link rel="stylesheet" href="<?php echo $baseUrl .'/css/css_003.css'; ?>">
	<link rel="stylesheet" href="<?php echo $baseUrl .'/css/css_002.css'; ?>">	
	<link href="<?php echo $baseUrl . '/css/font-awesome.css'; ?>" rel="stylesheet">
	<link href="<?php echo $baseUrl . '/css/default.css'; ?>" rel="stylesheet">
	<link href="<?php echo $baseUrl . '/css/bootstrap.min.css'; ?>" rel="stylesheet">
	<link href="<?php echo $baseUrl . '/css/css.css'; ?>" rel="stylesheet" type="text/css">

	<script src="<?php echo $baseUrl . '/js/jquery-1.js'; ?>"></script>	
	<script src="<?php echo $baseUrl . '/js/xenforo.js'; ?>"></script>
	<script src="<?php echo $baseUrl . '/js/quick_reply_profile.js'; ?>"></script>

</head>

<body data-twttr-rendered="true">

<div class="topHelper"></div>
<div id="headerMover">
	<div id="headerProxy"></div>

<div id="content" class="member_view">
	<div class="pageWidth">
		<div class="pageContent">
			<!-- main content area -->
		
		<?php include 'include/breadcrumbtop.php';?>

    
    <!---- content part------------> 
    <!----Right content part------------>
    <div class="row">
      <div class="col-lg-8" style="padding:0px;">
        <div class="right_content"> 
          

          
          <!----Add Part------------>
          <div class="add"> <img src="#" width="100%" height="100%" title="add box" class="img-rounded"> </div>
          <div class="row" style="height:50px; line-height:50px">
            
          </div>
          <!----right images content part------------>
           <div id="first"> 
		  <?php
function ordinal($num) {
    $ones = $num % 10;
    $tens = floor($num / 10) % 10;
    if ($tens == 1) {
        $suff = "th";
    } else {
        switch ($ones) {
            case 1 : $suff = "st"; break;
            case 2 : $suff = "nd"; break;
            case 3 : $suff = "rd"; break;
            default : $suff = "th";
        }
    }
    return $num . $suff;
}		  
		  $datas = $this->datas;
		  
     for($i = 0; $i<= count($datas)-1;$i++){ ?>
	
<!-- contains the content to be loaded when scrolled -->

  
<div class="second">
	<div class="row">
            <div class="col-lg-12" style="height:100px;">
              <div class="col-lg-2"> <img src="<?=$datas[$i]['logo'];?>" width="100" height="100" class="img-rounded"/> </div>
              <div class="col-lg-9">
                <div class="col-lg-12" style="text-align:center;">
                  <h3 style="padding:0px; margin:0px;"><?=$datas[$i]['gamename'];?></h3>
                </div>
                <div class="col-lg-12">
                  <div class="col-lg-4">
                    <h4>Week</h4>
                    <p class="h3"><?=ordinal($datas[$i]['week']);?></p>
                  </div>
                  <div class="col-lg-4">
                    <h4>Month</h4>
                    <p class="h3"><?=ordinal($datas[$i]['month']);?></p>
                  </div>
                  <div class="col-lg-4">
                    <h4>All time</h4>
                    <p class="h3"><?=ordinal($datas[$i]['all']);?></p>
                  </div>
                </div>
              </div>
            
          
</div>
</div>
</div>
          <hr>
		  
  <?php } ?>
  </div>
  
  
        </div>
      </div>
      
      <!----Left content part------------>
      <div class="col-lg-4" style="padding:0px;">
        <div class="left_content"> 
          
          <!----Add Box------------>
          <div class="row">
            <div class="col-lg-12">
              <div class="add_box"> <img src="#" width="100%" height="100%" title="add box" class="img-rounded"> </div>
            </div>
          </div>
          <!----Login Panel------------>
          <div class="row">
            <div class="col-lg-12">
              <div class="login_box">
                <h3>Login</h3>
                <div class="col-lg-12">
                  <div class="form_box"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      

     
		 </div>
        </div>
<?php include 'include/breadcrumbottom.php';?>
			
						
		</div>
	</div>
</div>

<?php include 'include/header.php';?>
</div>
<?php include 'include/footer.php';?>

			</body>
			</html>

