<?php
$imgbaseUrl = $this->baseUrl().'/img/';
$baseUrl = $this->baseUrl();
?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>U1stGame | Leader Board</title>
<link href="<?php echo $baseUrl . '/css/bootstrap.min.css'; ?>" media="all" rel="stylesheet" type="text/css" />
<link href="<?php echo $baseUrl . '/css/bootstrap-theme.min.css'; ?>" media="all" rel="stylesheet" type="text/css" />
<link href="<?php echo $baseUrl . '/css/default.css'; ?>" media="all" rel="stylesheet" type="text/css" />
<script src="<?php echo $baseUrl . '/owl-carousel/jquery-1.9.1.min.js';?>"></script>
<script src="<?php echo $baseUrl . '/js/jquery.masonry.min.js';?>"></script>
<script src="<?php echo $baseUrl . '/js/jquery.infinitescroll.min.js';?>"></script>

<script>
  $(function(){
 
    var $container = $('#first);
 document.write($container);
    $container.imagesLoaded(function(){
      $container.masonry({
        itemSelector: '.second',
        columnWidth: 40o
      });
    });
 
    $container.infinitescroll({
      navSelector  : '#page-nav',    // selector for the paged navigation
      nextSelector : '#page-nav a',  // selector for the NEXT link (to page 2)
      itemSelector : '.second',     // selector for all items you'll retrieve
      loading: {
          finishedMsg: 'No more pages to load.',
          img: 'http://i.imgur.com/6RMhx.gif'
        }
      },
      // trigger Masonry as a callback
      function( newElements ) {
        // hide new items while they are loading
        var $newElems = $( newElements ).css({ opacity: 0 });
        // ensure that images load before adding to masonry layout
        $newElems.imagesLoaded(function(){
          // show elems now they're ready
          $newElems.animate({ opacity: 1 });
          $container.masonry( 'appended', $newElems, true );
        });
      }
    );
  });
</script>

</head>


<body>
<div class="container-fluid" style="padding:0;">
  <div id="top"></div>
  <div class="container"> 
    
    <!---header--------->
    <header class="header"> 
      
      <!---Logo--------->
      <div class="col-lg-4" style="padding-top:5px;"> <img src=<?php echo $imgbaseUrl . 'logo3.png'?> width="190" height="50"> </div>
      
      <!---Social Icon--------->
      <div class="col-lg-8">
        <div class="col-lg-1 pull-right"><a href="#"><img src=<?php echo $imgbaseUrl .'facebook.png'?> width="30" height="30"></a></div>
        <div class="col-lg-1 pull-right"><a href="#"><img src=<?php echo $imgbaseUrl .'twitter.png'?> width="30" height="30"></a></div>
      </div>
    </header>
    
    <!---Menu Bar--------->
    <div class="row">
      <nav class="menu">
        <ul>
          <li><a href="#">Home</a></li>
          <li><a href="#">Form</a></li>
          <li><a href="#">Resources</a></li>
          <li><a href="#">Games</a></li>
          <li><a href="#">Bonus Feeds</a></li>
          <li><a href="#">Link Exchange</a></li>
        </ul>
      </nav>
    </div>
     <!---Breadcrumb Menu Bar--------->
    <div class="row">
      <div class="col-lg-12">
        <ul class="breadcrumb">
          <li><a href="#">Home</a></li>
          <li><a href="#">Games</a></li>
          <li class="active">Games Name</li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="search_form">
        <div class="col-lg-11">
          <input type="search" placeholder="Search Forums">
        </div>
        <div class="col-lg-1">
          <button type="submit" class="btn btn-default pull-left" style="margin:10px; height:30px; line-height:15px;">Go</button>
        </div>
      </div>
    </div>
    
    <!---- content part------------> 
    <!----Right content part------------>
    <div class="row">
      <div class="col-lg-8" style="padding:0px;">
        <div class="right_content"> 
          
          <!-------breadcrumbs--------->
          <div class="row">
            <div class="breadcrumbs"></div>
          </div>
          <!----Add Part------------>
          <div class="add"> <img src="#" width="100%" height="100%" title="add box" class="img-rounded"> </div>
          <div class="row">
            <div class="col-lg-12">
              <form class="form-horizontal">
                <div class="col-lg-1" style="height:50px; line-height:50px">Search</div>
                <input type="search" class="col-lg-9" placeholder="search games">
                <div class="col-lg-1">
                  <button type="submit" class="btn btn-default pull-left" style="margin:10px; height:30px; line-height:15px;">go</button>
                </div>
    
              </form>
            </div>
          </div>
          <!----right images content part------------>
		  
		  
		  <div id="first"> 
		  <?php
function ordinal($num) {
    $ones = $num % 10;
    $tens = floor($num / 10) % 10;
    if ($tens == 1) {
        $suff = "th";
    } else {
        switch ($ones) {
            case 1 : $suff = "st"; break;
            case 2 : $suff = "nd"; break;
            case 3 : $suff = "rd"; break;
            default : $suff = "th";
        }
    }
    return $num . $suff;
}		  
		  $datas = $this->datas;
		  
     for($i = 0; $i<= count($datas)-1;$i++){ ?>
	
<!-- contains the content to be loaded when scrolled -->

  
<div class="second">
	<div class="row">
            <div class="col-lg-12" style="height:100px;">
              <div class="col-lg-2"> <img src="<?=$datas[$i]['logo'];?>" width="100" height="100" class="img-rounded"/> </div>
              <div class="col-lg-9">
                <div class="col-lg-12" style="text-align:center;">
                  <h3 style="padding:0px; margin:0px;"><?=$datas[$i]['gamename'];?></h3>
                </div>
                <div class="col-lg-12">
                  <div class="col-lg-4">
                    <h4>Week</h4>
                    <p class="h3"><?=ordinal($datas[$i]['week']);?></p>
                  </div>
                  <div class="col-lg-4">
                    <h4>Month</h4>
                    <p class="h3"><?=ordinal($datas[$i]['month']);?></p>
                  </div>
                  <div class="col-lg-4">
                    <h4>All time</h4>
                    <p class="h3"><?=ordinal($datas[$i]['all']);?></p>
                  </div>
                </div>
              </div>
            
          
</div>
</div>
</div>
          <hr>
		  
  <?php } ?>
  </div>
          
		  <nav id="page-nav">
  <a href="http://localhost/repo/u1stgames/web_root/leaderboard/fetch/"></a>
</nav>
        
        </div>
      </div>
      
      <!----Left content part------------>
      <div class="col-lg-4" style="padding:0px;">
        <div class="left_content"> 
          
          <!----Add Box------------>
          <div class="row">
            <div class="col-lg-12">
              <div class="add_box"> <img src="#" width="100%" height="100%" title="add box" class="img-rounded"> </div>
            </div>
          </div>
          <!----Login Panel------------>
          <div class="row">
            <div class="col-lg-12">
              <div class="login_box">
                <h3>Login</h3>
                <div class="col-lg-12">
                  <div class="form_box"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-------------footer----------->
    <div class="row">
      <footer class="footer">
        <div class="sub_footer">
          <ul>
            <li><a href="#">FAQ</a></li>
            <li><a href="#">Developers</a></li>
            <li><a href="#">Terms</a></li>
            <li><a href="#">Thanks</a></li>
            <li><a href="#">Webmaster</a></li>
          </ul>
        </div>
      </footer>
    </div>
  </div>
</div>
</body>
</html>
